# Docker Compose over ride file for FreeCodeCamp
#
# Run with:
#   docker-compose -f docker-compose.yml -f docker-compose-shared.yml up
#
networks: # Used by by other projects like open-api
    shared:
        driver: bridge

version: "4"
services:
    db:  
    mailhog:
        networks:
            - shared 
        networks:
            - shared
    freecodecamp:
        networks:
            - shared

